export default {
    path: "/find",
    component: _=> import("@pages/find"),
    name:"find",
    meta:{
        flag:true,
        requireAuth:false,
        Tab:true,
        Mor:true,
    },
    children:[
        {
            path:"/find",
            redirect:"/find/findnews"
        },
        {
            path:"findnews",
            component:_=>import("@components/findnews"),
            name:"findnews",
            meta:{
                flag:true,
                requireAuth:false,
                Tab:true,
                Mor:true,
            }
        },
        {
            path:"findpai",
            component:_=>import("@components/findpai"),
            name:"findpai",
            meta:{
                flag:true,
                requireAuth:false,
                Tab:true,
                Mor:true,
            }
        },
        {
            path:"findping",
            component:_=>import("@components/findping"),
            name:"findping",
            meta:{
                flag:true,
                requireAuth:false,
                Tab:true,
                Mor:true,
            }
        },
        {
            path:"findyu",
            component:_=>import("@components/findyu"),
            name:"findyu",
            meta:{
                flag:true,
                requireAuth:false,
                Tab:true,
                Mor:true,
            }
        }
    ]
} 